FROM python:3.11.6-alpine
LABEL maintainer="jsdgfasjkhd@proton.me"

WORKDIR /root/
ADD . /root/

RUN apk add \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev

RUN pip install -r requirements.txt
RUN pip install -r requirements/mcp.txt
RUN chmod +x dirsearch.py

ENTRYPOINT ["./dirsearch.py"]
CMD ["--help"]
