from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from ipaddress import ip_address, ip_network
from typing import Any


@dataclass(frozen=True)
class FingerprintMatch:
    provider: str
    category: str
    technique: str
    signal: str
    confidence: float


@dataclass(frozen=True)
class FingerprintResult:
    provider: str | None = None
    category: str | None = None
    confidence: float = 0.0
    signals: tuple[str, ...] = ()
    headers_seen: Mapping[str, str] = field(default_factory=dict)
    behavior_tags: tuple[str, ...] = ()
    matches: tuple[FingerprintMatch, ...] = ()


TECHNIQUE_WEIGHTS = {
    "header": 3.0,
    "cookie": 2.5,
    "body_marker": 2.0,
    "tls_cert": 2.0,
    "cname_suffix": 1.5,
    "ip_cidr": 1.0,
}

CATEGORY_PREFERENCE = {
    "waf": 3,
    "cdn": 2,
    "common": 1,
}

HTTP_SIGNATURES = (
    {
        "provider": "cloudflare",
        "category": "waf",
        "headers": (
            ("cf-ray", "", 0.95),
            ("cf-cache-status", "", 0.85),
            ("cf-mitigated", "", 0.95),
            ("cf-chl-out", "", 0.95),
            ("server", "cloudflare", 0.85),
        ),
        "cookies": (("__cf_bm", 0.85), ("_cfuvid", 0.85), ("cf_clearance", 0.95)),
        "body_markers": (
            ("checking your browser", 0.75),
            ("cloudflare ray id", 0.85),
            ("cf-browser-verification", 0.85),
        ),
        "tls_cert": (("cloudflare", 0.85),),
    },
    {
        "provider": "akamai",
        "category": "cdn",
        "headers": (
            ("akamai-grn", "", 0.95),
            ("aka-global-request-id-uxtime", "", 0.95),
            ("x-akamai-transformed", "", 0.9),
            ("server-timing", "ak_p", 0.85),
            ("server", "akamai", 0.75),
        ),
        "cookies": (("_abck", 0.8), ("ak_bmsc", 0.85), ("bm_sz", 0.8)),
        "body_markers": (("reference #", 0.4), ("akamai", 0.65)),
        "tls_cert": (("akamai", 0.85),),
    },
    {
        "provider": "fastly",
        "category": "cdn",
        "headers": (
            ("fastly-debug-digest", "", 0.95),
            ("x-served-by", "cache-", 0.7),
            ("x-cache-hits", "", 0.65),
            ("x-timer", "", 0.65),
            ("server", "fastly", 0.85),
            ("via", "fastly", 0.85),
        ),
        "body_markers": (("fastly error", 0.85),),
        "tls_cert": (("fastly", 0.85),),
    },
    {
        "provider": "cloudfront",
        "category": "cdn",
        "headers": (
            ("x-amz-cf-id", "", 0.95),
            ("x-amz-cf-pop", "", 0.95),
            ("x-cache", "cloudfront", 0.85),
            ("via", "cloudfront", 0.85),
            ("server", "cloudfront", 0.85),
        ),
        "body_markers": (("generated by cloudfront", 0.9),),
        "tls_cert": (("amazon", 0.65), ("aws", 0.65)),
    },
    {
        "provider": "aws_waf",
        "category": "waf",
        "headers": (
            ("x-amzn-waf-action", "", 0.95),
            ("x-amzn-requestid", "", 0.45),
        ),
        "body_markers": (("aws waf", 0.9), ("request blocked", 0.6)),
    },
    {
        "provider": "incapsula",
        "category": "waf",
        "headers": (
            ("x-iinfo", "", 0.95),
            ("x-cdn", "incapsula", 0.9),
            ("x-ic-request-id", "", 0.9),
            ("x-incap-client-ip", "", 0.9),
            ("server", "incapsula", 0.8),
            ("server", "imperva", 0.8),
        ),
        "cookies": (("incap_ses", 0.9), ("visid_incap", 0.9)),
        "body_markers": (
            ("request unsuccessful. incapsula", 0.9),
            ("powered by imperva", 0.85),
            ("incident id", 0.5),
        ),
        "tls_cert": (("imperva", 0.85), ("incapsula", 0.85)),
    },
    {
        "provider": "sucuri",
        "category": "waf",
        "headers": (
            ("x-sucuri-id", "", 0.95),
            ("x-sucuri-cache", "", 0.85),
            ("x-sucuri-block", "", 0.95),
            ("server", "sucuri", 0.85),
        ),
        "body_markers": (("sucuri website firewall", 0.95), ("access denied - sucuri", 0.9)),
        "tls_cert": (("sucuri", 0.85),),
    },
    {
        "provider": "datadome",
        "category": "waf",
        "headers": (
            ("x-datadome", "", 0.95),
            ("datadome", "", 0.95),
        ),
        "cookies": (("datadome", 0.95),),
        "body_markers": (("datadome", 0.9),),
    },
    {
        "provider": "f5_bigip",
        "category": "waf",
        "headers": (
            ("x-wa-info", "", 0.8),
            ("x-f5", "", 0.8),
            ("server", "big-ip", 0.75),
            ("server", "bigip", 0.75),
        ),
        "cookies": (("bigipserver", 0.9), ("f5avrbbbbbbbbbbbb", 0.9)),
        "body_markers": (("the requested url was rejected", 0.65),),
    },
    {
        "provider": "barracuda",
        "category": "waf",
        "headers": (
            ("x-barracuda", "", 0.9),
            ("server", "barracuda", 0.8),
        ),
        "cookies": (("barra_counter_session", 0.9), ("bni_", 0.75)),
        "body_markers": (("barracuda web application firewall", 0.95),),
        "tls_cert": (("barracuda", 0.85),),
    },
    {
        "provider": "cloudbric",
        "category": "waf",
        "headers": (("x-cloudbric", "", 0.95),),
        "cookies": (("cloudbric", 0.9),),
        "body_markers": (("cloudbric", 0.9),),
        "tls_cert": (("cloudbric", 0.85),),
    },
    {
        "provider": "azure_front_door",
        "category": "cdn",
        "headers": (
            ("x-azure-ref", "", 0.95),
            ("x-fd-int-roxy-purgeid", "", 0.9),
        ),
        "tls_cert": (("microsoft azure", 0.75), ("azure", 0.55)),
    },
)


def fingerprint_headers(
    headers: Mapping[str, str] | Iterable[tuple[str, str]],
    *,
    dataset: Mapping[str, Any] | None = None,
    behavior_tags: Iterable[str] = (),
) -> FingerprintResult:
    return fingerprint_response(headers, dataset=dataset, behavior_tags=behavior_tags)


def fingerprint_response(
    headers: Mapping[str, str] | Iterable[tuple[str, str]],
    *,
    body: str | bytes = "",
    dns_cnames: Iterable[str] = (),
    resolved_ips: Iterable[str] = (),
    tls_cert: Mapping[str, Any] | Iterable[str] | str | None = None,
    dataset: Mapping[str, Any] | None = None,
    behavior_tags: Iterable[str] = (),
) -> FingerprintResult:
    normalized = _normalize_headers(headers)
    matches = []
    matches.extend(_match_http_signatures(normalized, body, tls_cert))
    matches.extend(_match_cname_suffixes(dns_cnames, dataset))
    matches.extend(_match_ip_cidrs(resolved_ips, dataset))
    matches = _dedupe_matches(matches)
    provider, category, confidence = _select_primary_match(matches, behavior_tags)

    return FingerprintResult(
        provider=provider,
        category=category,
        confidence=confidence,
        signals=tuple(dict.fromkeys(match.signal for match in matches)),
        headers_seen=normalized,
        behavior_tags=tuple(dict.fromkeys(behavior_tags)),
        matches=tuple(matches),
    )


def merge_fingerprints(
    fingerprints: Iterable[FingerprintResult],
    *,
    behavior_tags: Iterable[str] = (),
) -> FingerprintResult:
    fingerprints = tuple(fingerprints)
    headers: dict[str, str] = {}
    signals: list[str] = []
    tags: list[str] = list(behavior_tags)
    matches: list[FingerprintMatch] = []

    for fingerprint in fingerprints:
        headers.update(fingerprint.headers_seen)
        signals.extend(fingerprint.signals)
        tags.extend(fingerprint.behavior_tags)
        matches.extend(fingerprint.matches)
        if fingerprint.provider and not fingerprint.matches:
            matches.append(
                FingerprintMatch(
                    fingerprint.provider,
                    fingerprint.category or "common",
                    "legacy",
                    f"legacy:{fingerprint.provider}",
                    fingerprint.confidence,
                )
            )

    matches = _dedupe_matches(matches)
    provider, category, confidence = _select_primary_match(matches, tags)

    return FingerprintResult(
        provider=provider,
        category=category,
        confidence=confidence,
        signals=tuple(dict.fromkeys(signals + [match.signal for match in matches])),
        headers_seen=headers,
        behavior_tags=tuple(dict.fromkeys(tags)),
        matches=tuple(matches),
    )


def _match_http_signatures(
    headers: Mapping[str, str],
    body: str | bytes,
    tls_cert: Mapping[str, Any] | Iterable[str] | str | None,
) -> list[FingerprintMatch]:
    matches: list[FingerprintMatch] = []
    lowered_headers = {name: value.lower() for name, value in headers.items()}
    cookie_source = "; ".join(
        value for name, value in lowered_headers.items() if name in ("set-cookie", "cookie")
    )
    body_text = _normalize_text(body[:4096] if isinstance(body, bytes) else str(body)[:4096])
    tls_text = _normalize_tls_cert_text(tls_cert)

    for signature in HTTP_SIGNATURES:
        provider = str(signature["provider"])
        category = str(signature["category"])
        for name, value_pattern, confidence in signature.get("headers", ()):
            value = lowered_headers.get(name)
            if value is None:
                continue
            if value_pattern and str(value_pattern).lower() not in value:
                continue
            matches.append(
                FingerprintMatch(
                    provider,
                    category,
                    "header",
                    f"header:{name}",
                    float(confidence),
                )
            )

        for marker, confidence in signature.get("cookies", ()):
            marker = str(marker).lower()
            if marker in cookie_source:
                matches.append(
                    FingerprintMatch(
                        provider,
                        category,
                        "cookie",
                        f"cookie:{marker}",
                        float(confidence),
                    )
                )

        for marker, confidence in signature.get("body_markers", ()):
            marker = str(marker).lower()
            if marker in body_text:
                matches.append(
                    FingerprintMatch(
                        provider,
                        category,
                        "body_marker",
                        f"body_marker:{marker}",
                        float(confidence),
                    )
                )

        for marker, confidence in signature.get("tls_cert", ()):
            marker = str(marker).lower()
            if marker in tls_text:
                matches.append(
                    FingerprintMatch(
                        provider,
                        category,
                        "tls_cert",
                        f"tls_cert:{marker}",
                        float(confidence),
                    )
                )

    return matches


def _match_cname_suffixes(
    cnames: Iterable[str],
    dataset: Mapping[str, Any] | None,
) -> list[FingerprintMatch]:
    suffixes = _cname_suffixes(dataset)
    if not suffixes:
        return []

    matches: list[FingerprintMatch] = []
    for cname in cnames:
        normalized = _normalize_hostname(cname)
        if not normalized:
            continue
        for provider, suffix in suffixes:
            if normalized == suffix or normalized.endswith(f".{suffix}"):
                matches.append(
                    FingerprintMatch(
                        provider,
                        "common",
                        "cname_suffix",
                        f"cname_suffix:{suffix}",
                        0.65,
                    )
                )
    return matches


def _match_ip_cidrs(
    ips: Iterable[str],
    dataset: Mapping[str, Any] | None,
) -> list[FingerprintMatch]:
    networks = _cidr_networks(dataset)
    matches: list[FingerprintMatch] = []
    for raw_ip in ips:
        try:
            address = ip_address(str(raw_ip))
        except ValueError:
            continue

        for category in ("cdn", "waf"):
            for provider, provider_networks in networks.get(category, {}).items():
                for network in provider_networks:
                    if address in network:
                        matches.append(
                            FingerprintMatch(
                                provider,
                                category,
                                "ip_cidr",
                                f"ip_cidr:{network.with_prefixlen}",
                                0.58 if category == "waf" else 0.52,
                            )
                        )
                        break
    return matches


def _select_primary_match(
    matches: Iterable[FingerprintMatch],
    behavior_tags: Iterable[str] = (),
) -> tuple[str | None, str | None, float]:
    matches = tuple(matches)
    if not matches:
        return (None, None, 0.4) if tuple(behavior_tags) else (None, None, 0.0)

    provider_scores: dict[str, float] = defaultdict(float)
    provider_categories: dict[str, dict[str, float]] = defaultdict(lambda: defaultdict(float))
    provider_max_confidence: dict[str, float] = defaultdict(float)
    provider_http: dict[str, bool] = defaultdict(bool)

    for match in matches:
        score = TECHNIQUE_WEIGHTS.get(match.technique, 1.0) * match.confidence
        provider_scores[match.provider] += score
        provider_categories[match.provider][match.category] += score
        provider_max_confidence[match.provider] = max(
            provider_max_confidence[match.provider],
            match.confidence,
        )
        if match.technique in {"header", "cookie", "body_marker", "tls_cert"}:
            provider_http[match.provider] = True

    def provider_rank(provider: str) -> tuple[float, int, int, float, str]:
        category = _best_category(provider_categories[provider])
        return (
            provider_scores[provider],
            int(provider_http[provider]),
            CATEGORY_PREFERENCE.get(category or "", 0),
            provider_max_confidence[provider],
            provider,
        )

    provider = max(provider_scores, key=provider_rank)
    category = _best_category(provider_categories[provider])
    selected_matches = [match for match in matches if match.provider == provider]
    confidence = min(
        1.0,
        max(match.confidence for match in selected_matches)
        + 0.1 * max(0, len({match.signal for match in selected_matches}) - 1),
    )
    return provider, category, confidence


def _best_category(category_scores: Mapping[str, float]) -> str | None:
    if not category_scores:
        return None
    return max(
        category_scores,
        key=lambda category: (
            category_scores[category],
            CATEGORY_PREFERENCE.get(category, 0),
            category,
        ),
    )


def _dedupe_matches(matches: Iterable[FingerprintMatch]) -> list[FingerprintMatch]:
    deduped: dict[tuple[str, str, str, str], FingerprintMatch] = {}
    for match in matches:
        key = (match.provider, match.category, match.technique, match.signal)
        current = deduped.get(key)
        if current is None or match.confidence > current.confidence:
            deduped[key] = match
    return list(deduped.values())


def _normalize_headers(headers: Mapping[str, str] | Iterable[tuple[str, str]]) -> dict[str, str]:
    if hasattr(headers, "items"):
        pairs = headers.items()
    else:
        pairs = headers

    return {str(key).lower(): str(value) for key, value in pairs}


def _normalize_text(value: str | bytes) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="ignore").lower()
    return str(value).lower()


def _normalize_tls_cert_text(tls_cert: Mapping[str, Any] | Iterable[str] | str | None) -> str:
    if tls_cert is None:
        return ""
    if isinstance(tls_cert, str):
        return tls_cert.lower()
    if isinstance(tls_cert, Mapping):
        values: list[str] = []
        for value in tls_cert.values():
            if isinstance(value, (list, tuple, set)):
                values.extend(str(item) for item in value)
            else:
                values.append(str(value))
        return " ".join(values).lower()
    return " ".join(str(value) for value in tls_cert).lower()


def _normalize_hostname(hostname: str) -> str:
    return str(hostname).strip().lower().rstrip(".")


def _dataset_categories(dataset: Mapping[str, Any] | None) -> Mapping[str, Any]:
    if not dataset:
        return {}

    categories = dataset.get("categories", {})
    if isinstance(categories, Mapping):
        return categories

    return {}


def _cname_suffixes(dataset: Mapping[str, Any] | None) -> tuple[tuple[str, str], ...]:
    common = _dataset_categories(dataset).get("common", {})
    if not isinstance(common, Mapping):
        return ()

    suffixes: list[tuple[str, str]] = []
    for provider, values in common.items():
        if not isinstance(values, Iterable) or isinstance(values, (str, bytes)):
            continue
        for value in values:
            suffix = _normalize_hostname(value)
            if suffix:
                suffixes.append((str(provider).lower(), suffix))
    return tuple(suffixes)


def _cidr_networks(dataset: Mapping[str, Any] | None) -> dict[str, dict[str, tuple[Any, ...]]]:
    categories = _dataset_categories(dataset)
    compiled: dict[str, dict[str, tuple[Any, ...]]] = {"cdn": {}, "waf": {}}
    for category in ("cdn", "waf"):
        providers = categories.get(category, {})
        if not isinstance(providers, Mapping):
            continue
        for provider, cidrs in providers.items():
            if not isinstance(cidrs, Iterable) or isinstance(cidrs, (str, bytes)):
                continue
            networks = []
            for cidr in cidrs:
                try:
                    networks.append(ip_network(str(cidr), strict=False))
                except ValueError:
                    continue
            compiled[category][str(provider).lower()] = tuple(networks)
    return compiled
